# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e8e377b31f5b2333b0eba575d5ffc9fe3df04ec4dac94548428f60b082c9d906a25b3916f2e66c7431c1208c3ee396e18f03790baffd828051b8de8c1518680

test:
  secret_key_base: 75297e15de87099bc73a4e25760098293bac31ec5504914b17cd671dbf5e8b165ee2066790fec4ee444e5ad14056f01a353b02d10ec08d5e3b1b7f196732cd70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
