# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d17020367f68aae367c497b079683ee701b8622597379394fbd1a6c368d09f3599dc9c405ac4a56490d12d39aa96d83755850d92872747480af2c04e59a9fde1

test:
  secret_key_base: 62b47df42a25c1b2491c0a286e01461a0258f60e5835fa4815360c75736d73b15ebaf81b7613e1a5d139591b79bd9202739153b0c7bcd609b7e3c60426432aec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
